import {AI_ACTIONS,type Action,type CombatState,type ControlFrame,type Decision,type Policy,type SpatialWorld} from './types';
import {offlineDecision,POLICY_TEXT} from './policy';
type DoomModule={FS:{mkdir:(p:string)=>void;writeFile:(p:string,d:string|Uint8Array)=>void};callMain:(a:string[])=>void;ccall:(n:string,r:string|null,t:string[],a:unknown[])=>unknown};
export type EngineObservation={ready:boolean;player?:{health:number;armor:number;weapon:number;ammo:{bullets:number;shells:number;rockets:number;cells:number};recent_damage:number;under_fire:boolean;x:number;y:number;angle:number;kills:number};engine_state?:{gametic:number;gamestate:number;paused:boolean;controls:number};visible_enemies?:Array<{id:string;distance_units:number;health:number;attacking:boolean;threat:string}>;visible_pickups?:Array<{id:string;type:string;distance_units:number;reachable:boolean}>;navigation?:{exit_known:boolean};world?:SpatialWorld;motion?:{distance:number;stuck:boolean;total_distance:number};exploration?:{visited_cells:number;current_cell_visits:number;novelty:number};engine?:string};
export type Runner={module:DoomModule;canvas:HTMLCanvasElement;policy:Policy;systemPrompt:string;rng:number;visitedCells:Map<string,number>;lastPosition?:{x:number;y:number};stuckTicks:number;distanceTravelled:number;observation:EngineObservation;decision:Decision;history:string[];fallback:boolean;busy:boolean;controlEpoch:number};
const engineUrl='/engine/chocolate-doom.js';
let gameData:Promise<ArrayBuffer>|undefined;
function preloadGameData(){return gameData??=fetch('/engine/chocolate-doom.data').then(response=>{if(!response.ok)throw new Error(`Game data unavailable: ${response.status}`);return response.arrayBuffer()})}
function useStableEngineDpi(){const descriptor=Object.getOwnPropertyDescriptor(window,'devicePixelRatio');if(descriptor?.configurable)Object.defineProperty(window,'devicePixelRatio',{configurable:true,get:()=>1})}
function simplifyInterface(){if(document.querySelector('#essential-interface'))return;const style=document.createElement('style');style.id='essential-interface';style.textContent='.eyebrow,.lede,.method,.engine-note,footer,.specimen,.telemetry small,.probs{display:none}.panel-head{min-height:56px;align-items:center}.prompt-control{padding:10px 18px}.prompt-control label span{display:none}.telemetry{min-height:108px}.restart{height:27px;margin-left:auto;padding:0 8px;font-size:8px;color:var(--muted)}';document.head.append(style)}
function mkdir(fs:DoomModule['FS'],p:string){try{fs.mkdir(p)}catch{}}
export async function boot(canvas:HTMLCanvasElement,policy:Policy):Promise<Runner>{
  simplifyInterface();
  const heading=canvas.closest('article')?.querySelector('.panel-head');
  if(heading&&!heading.querySelector('.restart')){const restart=document.createElement('button');restart.className='restart';restart.type='button';restart.textContent='RESTART COMPARISON';restart.title='Restarts both isolated game instances';restart.addEventListener('click',()=>location.reload());heading.append(restart)}
  const controls=document.querySelector('.controls');
  if(controls&&!controls.querySelector('#stop-api')){const stop=document.createElement('button');stop.id='stop-api';stop.type='button';stop.textContent='STOP API';stop.addEventListener('click',async()=>{await fetch('/api/stop',{method:'POST'});stop.textContent='API STOPPED';stop.disabled=true});controls.append(stop)}
  useStableEngineDpi();
  const [data,{default:create}]=await Promise.all([preloadGameData(),(0,eval)(`import(${JSON.stringify(engineUrl)})`)]);let module!:DoomModule;
  module=await create({canvas,keyboardListeningElement:canvas,locateFile:(p:string)=>`/engine/${p}`,getPreloadedPackage:()=>data,noInitialRun:true,preRun:[(m:DoomModule)=>{mkdir(m.FS,'/config');mkdir(m.FS,'/savegames');m.FS.writeFile('/config/default.cfg','fullscreen 0\ngrabmouse 0\nuse_mouse 0\n');m.FS.writeFile('/config/chocolate-doom.cfg','aspect_ratio_correct 1\ninteger_scaling 0\nscreenblocks 10\nsmooth_pixel_scaling 0\nforce_software_renderer 1\n')}],print:()=>{},printErr:()=>{}});
  try{module.callMain(['-window','-iwad','/iwads/freedoom2.wad','-warp','1','-skill','1','-nomusic','-nosound','-config','/config/default.cfg','-extraconfig','/config/chocolate-doom.cfg'])}catch(e){const s=String(e);if(!s.includes('unwind')&&!s.includes('SimulateInfiniteLoop'))throw e}
  const empty:any={player:{health:42,armor:10,weapon:'shotgun',ammo:{shells:8,bullets:50},recent_damage:0,under_fire:false},visible_enemies:[],visible_pickups:[],navigation:{cover:[],unexplored_directions:['forward'],exit_known:false,exit_direction:'unknown'},history:{previous_action:'EXPLORE',current_intent:'explore',stuck_probability:0},policy:POLICY_TEXT[policy]};
  const runner:Runner={module,canvas,policy,systemPrompt:POLICY_TEXT[policy],rng:(Date.now()^(policy==='survivalist'?0x51a7:0xb3e5))>>>0,visitedCells:new Map(),stuckTicks:0,distanceTravelled:0,observation:{ready:false},decision:offlineDecision(empty,policy),history:[],fallback:false,busy:false,controlEpoch:0};
  return runner;
}
export function observe(r:Runner):EngineObservation{try{const next=JSON.parse(r.module.ccall('PromptFPS_Observation','string',[],[]) as string)as EngineObservation,p=next.player;if(p){const previous=r.lastPosition,delta=previous?Math.hypot(p.x-previous.x,p.y-previous.y):0,moving=/EXPLORE_|MOVE_TO_|RETREAT_FROM_|COLLECT_|USE_NEAREST/.test(r.decision.action);r.distanceTravelled+=delta;r.stuckTicks=moving&&previous&&delta<2?r.stuckTicks+1:0;r.lastPosition={x:p.x,y:p.y};next.motion={distance:delta,stuck:r.stuckTicks>=3,total_distance:r.distanceTravelled};const cell=`${Math.floor(p.x/128)},${Math.floor(p.y/128)}`,visits=(r.visitedCells.get(cell)??0)+1;r.visitedCells.set(cell,visits);next.exploration={visited_cells:r.visitedCells.size,current_cell_visits:visits,novelty:1/visits}}r.observation=next;window.__SPATIAL_SNAPSHOT__=next;const index=Number(r.canvas.id.split('-').pop()??0);(window.__ENGINE_STATES__??=[])[index]=next;return next}catch(error){window.__SPATIAL_ERROR__=String(error);console.error('Spatial bridge error',error);return{ready:false}}}
export function initializeStart(r:Runner){r.module.ccall('PromptFPS_SetStart',null,[],[])}
export function setPaused(r:Runner,paused:boolean){r.module.ccall('PromptFPS_SetPaused',null,['number'],[paused?1:0])}
const C={FORWARD:1,BACK:2,LEFT:4,RIGHT:8,STRAFE_LEFT:16,STRAFE_RIGHT:32,FIRE:64,USE:128}as const;
function turnMask(relativeAngle:number){if(Math.abs(relativeAngle)<=0x04000000)return 0;return relativeAngle>0?C.LEFT:C.RIGHT}
function nextRandom(r:Runner){r.rng=(Math.imul(r.rng,1664525)+1013904223)>>>0;return r.rng/4294967296}
function pointAngle(r:Runner,x:number,y:number){const p=r.observation.player;if(!p)return 0;const desired=Math.atan2(y-p.y,x-p.x),doom=(desired<0?desired+Math.PI*2:desired)/(Math.PI*2)*0x100000000;return(doom-p.angle)|0}
type Point={x:number;y:number};
function crosses(a:Point,b:Point,c:Point,d:Point){const side=(p:Point,q:Point,r:Point)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x);return side(a,b,c)*side(a,b,d)<0&&side(c,d,a)*side(c,d,b)<0}
function clearPath(world:SpatialWorld,a:Point,b:Point){return !world.lines.some(line=>line.blocking&&crosses(a,b,{x:line.x1,y:line.y1},{x:line.x2,y:line.y2}))}
function nextWaypoint(world:SpatialWorld,start:Point,goal:Point){if(clearPath(world,start,goal))return goal;const candidates=world.lines.filter(line=>line.blocking&&crosses(start,goal,{x:line.x1,y:line.y1},{x:line.x2,y:line.y2})).flatMap(line=>[{x:line.x1,y:line.y1},{x:line.x2,y:line.y2}]).filter(point=>clearPath(world,start,point));return candidates.sort((a,b)=>Math.hypot(a.x-start.x,a.y-start.y)+Math.hypot(a.x-goal.x,a.y-goal.y)-Math.hypot(b.x-start.x,b.y-start.y)-Math.hypot(b.x-goal.x,b.y-goal.y))[0]??goal}
function useLineMask(r:Runner,activate:boolean){const world=r.observation.world,p=r.observation.player;if(!world||!p)return 0;const line=[...world.lines].filter(x=>x.special!==0).sort((x,y)=>Math.hypot((x.x1+x.x2)/2-p.x,(x.y1+x.y2)/2-p.y)-Math.hypot((y.x1+y.x2)/2-p.x,(y.y1+y.y2)/2-p.y))[0];if(!line)return activate?C.USE:0;const goal={x:(line.x1+line.x2)/2,y:(line.y1+line.y2)/2},waypoint=nextWaypoint(world,p,goal),distance=Math.hypot(goal.x-p.x,goal.y-p.y);return turnMask(pointAngle(r,waypoint.x,waypoint.y))|(distance<64?(activate?C.USE:0):C.FORWARD)}
function motorMask(r:Runner,a:Action){const world=r.observation.world,p=r.observation.player;if(a==='IDLE')return 0;if(a==='FIRE')return C.FIRE;if(a==='EXPLORE_WORLD'){const roll=nextRandom(r);if(r.observation.motion?.stuck)return C.BACK|(roll<.5?C.LEFT:C.RIGHT);return C.FORWARD|(roll<.16?C.LEFT:roll>.84?C.RIGHT:0)}if(a==='USE_NEAREST_LINE')return useLineMask(r,true);if(!world||!p)return 0;const candidates=a==='COLLECT_NEAREST_PICKUP'?world.entities.filter(x=>x.pickup):world.entities.filter(x=>x.enemy&&x.health>0),nearest=[...candidates].sort((x,y)=>x.distance-y.distance)[0];if(!nearest)return a==='FACE_ENEMY'?C.RIGHT:0;const waypoint=a==='RETREAT_FROM_ENEMY'||a==='FACE_ENEMY'?nearest:nextWaypoint(world,p,nearest),turn=turnMask(pointAngle(r,waypoint.x,waypoint.y));if(a==='FACE_ENEMY')return turn;if(a==='RETREAT_FROM_ENEMY')return C.BACK;if(a==='COLLECT_NEAREST_PICKUP')return turn|C.FORWARD;return turn|C.FORWARD}
function frameMask(r:Runner,frame:ControlFrame){let mask=0;if(frame.movement==='EXPLORE_WORLD')mask|=motorMask(r,'EXPLORE_WORLD');if(frame.movement==='MOVE_TO_ENEMY')mask|=motorMask(r,'MOVE_TO_ENEMY');if(frame.movement==='RETREAT_FROM_ENEMY')mask|=motorMask(r,'RETREAT_FROM_ENEMY');if(frame.movement==='COLLECT_NEAREST_PICKUP')mask|=motorMask(r,'COLLECT_NEAREST_PICKUP');if(frame.movement==='MOVE_TO_USE')mask|=useLineMask(r,frame.interaction==='USE');if(frame.view==='SCAN')mask|=C.RIGHT;if(frame.view==='FACE_ENEMY')mask|=motorMask(r,'FACE_ENEMY');if(frame.trigger==='FIRE')mask|=C.FIRE;if(frame.interaction==='USE'&&frame.movement!=='MOVE_TO_USE')mask|=C.USE;return mask}
export function execute(r:Runner,input:Action|ControlFrame,duration=180){const mask=typeof input==='string'?motorMask(r,input):frameMask(r,input),epoch=++r.controlEpoch,actions=typeof input==='string'?[input]:[input.movement==='MOVE_TO_USE'?'USE_NEAREST_LINE':input.movement,input.view==='FACE_ENEMY'?'FACE_ENEMY':null].filter(Boolean)as Action[],selectors=actions.map(action=>`[data-control="${action}"]`);if(typeof input!=='string'&&input.trigger==='FIRE')selectors.push('[data-control="SHOOT"]');const buttons=selectors.map(selector=>r.canvas.closest('article')?.querySelector<HTMLButtonElement>(selector)).filter(Boolean)as HTMLButtonElement[];r.canvas.focus();buttons.forEach(button=>button.classList.add('active'));r.module.ccall('PromptFPS_SetControls',null,['number'],[mask]);setTimeout(()=>{if(r.controlEpoch===epoch)r.module.ccall('PromptFPS_SetControls',null,['number'],[0]);buttons.forEach(button=>button.classList.remove('active'));setTimeout(()=>observe(r),40)},duration)}
export function detectCombat(o:EngineObservation):CombatState{const fighting_distance=384,aim_tolerance=0x04000000,enemies=(o.world?.entities??[]).filter(entity=>entity.enemy&&entity.health>0&&entity.visible).sort((a,b)=>a.distance-b.distance),enemy=enemies[0];return{enemy_detected:Boolean(enemy),visible_enemy_count:enemies.length,fighting_distance,aim_tolerance,...(enemy?{nearest_visible_enemy:{id:enemy.id,type:enemy.type,health:enemy.health,distance:enemy.distance,relative_angle:enemy.relative_angle,aligned:Math.abs(enemy.relative_angle)<=aim_tolerance,in_fighting_range:enemy.distance<=fighting_distance,targeting_player:enemy.targeting_player}}:{})}}
export function toTacticalState(o:EngineObservation,p:Policy,previous:Action){const pl=o.player;return{game_context:{title:'Freedoom running on Chocolate Doom',genre:'real-time first-person shooter',objective:'Survive, defeat hostile monsters, collect useful resources, activate doors and switches, explore the level, and reach the exit.',combat:'Movement, view direction, weapon trigger, and interaction are independent. Approach without firing until the target is visible, aligned, and in range.',navigation:'The world is a 2D walkable map represented by entity coordinates and blocking linedefs. Exploration, enemy approach, retreat, pickup collection, and line use are separate movement choices.',decision_model:'Choose a composable control frame each interval: movement + view + trigger + interaction.'},player:{health:pl?.health??42,armor:pl?.armor??10,weapon:['fist','pistol','shotgun','chaingun','rocket_launcher','plasma','bfg','chainsaw','super_shotgun'][pl?.weapon??2]??'unknown',ammo:pl?.ammo??{shells:0,bullets:0,rockets:0,cells:0},recent_damage:pl?.recent_damage??0,under_fire:pl?.under_fire??false,x:pl?.x??0,y:pl?.y??0,angle:pl?.angle??0,motion:o.motion},visible_enemies:(o.visible_enemies??[]).map(e=>({...e,distance:e.distance_units<256?'near':e.distance_units<768?'medium':'far',direction:'engine_relative',type:'doom_monster'})),visible_pickups:(o.visible_pickups??[]).map(x=>({...x,distance:x.distance_units<128?'near':'medium',direction:'engine_relative'})),navigation:{cover:[],unexplored_directions:['forward','left','right'],exit_known:o.navigation?.exit_known??false,exit_direction:'unknown'},combat:detectCombat(o),exploration:o.exploration,history:{previous_action:previous,current_intent:'survive_level',stuck_probability:o.motion?.stuck?1:0},policy:POLICY_TEXT[p],world:o.world,controls:AI_ACTIONS,source:{engine:'Chocolate Doom 3.1.1 native state bridge',raw_pixels_sent:false,spatial_data:'native combat sensor, entity pose, exploration memory, motion, collision bounds, visibility, targeting, and blocking linedef geometry with waypoint planning'}}}
