import'./style.css';
import{boot,execute,initializeStart,observe,toTacticalState,type Runner}from'./doom';
import{offlineDecision,POLICY_TEXT}from'./policy';
import{type Action,type ControlFrame,type Policy}from'./types';
const q=new URLSearchParams(location.search),selected=(location.pathname.includes('berserker')?'berserker':'survivalist')as Policy,policies=[selected];
let runners:Runner[]=[],mode:'offline'|'live'='offline',started=false,deathHandled=false,deathMonitor=0,timers:number[]=[],initializePromise:Promise<void>;
const app=document.querySelector('#app')!;
app.innerHTML=`<main><header><div class="title"><h1>Prompt FPS / single agent</h1></div><div class="controls"><span id="badge" class="badge offline"><i></i>DRY RUN</span><button id="settings">API ACCESS</button><button id="start" class="primary">RUN</button></div></header><section class="key-panel" id="key-panel" hidden><form id="key-form"><label>TypeSafe API key <input id="key" type="password" autocomplete="off" required></label><button>CONNECT</button></form></section><section class="arena single">${policies.map((p,i)=>`<article><div class="panel-head"><h2>DOOM AGENT</h2></div><div class="prompt-control"><label>System prompt</label><textarea id="prompt-${i}" rows="3">${POLICY_TEXT[p]}</textarea></div><div class="experiment"><div class="game-column"><div class="screen"><canvas id="doom-${i}" width="320" height="200" tabindex="0"></canvas><div class="loading" id="loading-${i}">INITIALIZING ENGINE</div></div><div class="control-pad" aria-label="Agent essential actions"><button data-control="EXPLORE_WORLD">EXPLORE</button><button data-control="MOVE_TO_ENEMY">APPROACH</button><button data-control="RETREAT_FROM_ENEMY">RETREAT</button><button data-control="SHOOT">SHOOT</button></div><div class="telemetry" id="telemetry-${i}"><b>AWAITING RUN</b></div></div><aside class="api-console"><div class="console-head"><b>API EVENT STREAM</b><button type="button" data-clear-console>CLEAR</button></div><pre id="console-${i}" aria-live="polite">READY\n</pre></aside></div></article>`).join('')}</section></main>`;
const badge=document.querySelector('#badge')!,start=document.querySelector<HTMLButtonElement>('#start')!,keyPanel=document.querySelector<HTMLElement>('#key-panel')!;
document.querySelector('#settings')!.addEventListener('click',()=>keyPanel.hidden=!keyPanel.hidden);
document.querySelector('#key-form')!.addEventListener('submit',async e=>{e.preventDefault();const input=document.querySelector<HTMLInputElement>('#key')!,key=input.value.trim();input.value='';const response=await fetch('/api/key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({key})});if(!response.ok){badge.textContent='KEY REJECTED';return}mode='live';badge.className='badge live';badge.innerHTML='<i></i>LIVE AI CONTROL';keyPanel.hidden=true});
function debug(r:Runner,update:Record<string,unknown>){const index=runners.indexOf(r),items=(window.__AI_DEBUG__??=[]),previous=(items[index]??{})as Record<string,unknown>;items[index]={...previous,runner:index+1,...update};window.__AI_DEBUG__=items}
function logEvent(r:Runner,label:string,value?:unknown){const index=runners.indexOf(r),output=document.querySelector<HTMLPreElement>(`#console-${index}`);if(!output)return;const time=new Date().toLocaleTimeString([],{hour12:false});output.textContent+=`[${time}] ${label}${value===undefined?'':`\n${JSON.stringify(value,null,2)}`}\n`;output.scrollTop=output.scrollHeight}
async function stopOnDeath(r:Runner){if(deathHandled||!r.observation.player||r.observation.player.health>0)return false;deathHandled=true;started=false;clearInterval(deathMonitor);timers.forEach(clearTimeout);timers=[];execute(r,'IDLE',0);start.disabled=true;start.textContent='AGENT DEAD';badge.className='badge offline';badge.innerHTML='<i></i>DEAD · API STOPPED';debug(r,{request_status:'stopped_on_death',death_detected_at:new Date().toISOString()});logEvent(r,'PLAYER DEATH · API STOPPED',{tick:r.observation.engine_state?.gametic,health:r.observation.player.health});try{await fetch('/api/stop',{method:'POST'})}catch(error){logEvent(r,'STOP REQUEST FAILED',String(error))}return true}
async function decide(r:Runner){if(await stopOnDeath(r)||r.busy||!r.observation.ready)return;r.busy=true;const state=toTacticalState(r.observation,r.policy,r.decision.action),index=runners.indexOf(r);state.policy=r.systemPrompt;debug(r,{state_updated_at:new Date().toISOString(),engine_tick:r.observation.engine_state?.gametic,state_sent:{player:state.player,combat:state.combat,exploration:state.exploration,visible_enemies:state.visible_enemies.length,entities:state.world?.entities.length??0,lines:state.world?.lines.length??0,controls:state.controls},request_status:mode==='live'?'pending':'dry_run',error:null});logEvent(r,mode==='live'?'REQUEST SENT':'DRY-RUN STATE',{tick:r.observation.engine_state?.gametic,enemies:state.combat.visible_enemy_count,nearest:state.combat.nearest_visible_enemy});try{if(mode==='live'){const response=await fetch('/api/decision',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state,prompt:r.systemPrompt})}),body=await response.json();if(!response.ok)throw new Error(String(body.error??`HTTP_${response.status}`));r.decision=body;debug(r,{request_status:'complete',response_received_at:new Date().toISOString(),api_response:body});logEvent(r,'API RESPONSE',body)}else{r.decision=offlineDecision(state as any,r.policy);debug(r,{request_status:'dry_run',api_response:r.decision});logEvent(r,'LOCAL DECISION',r.decision.frame)}r.fallback=false}catch(error){r.decision=offlineDecision(state as any,r.policy);r.fallback=true;debug(r,{request_status:'failed',response_received_at:new Date().toISOString(),error:String(error),fallback_decision:r.decision});logEvent(r,'API ERROR · FALLBACK',{error:String(error),frame:r.decision.frame});try{const status=await fetch('/api/key').then(response=>response.json());if(!status.configured){mode='offline';badge.className='badge offline';badge.innerHTML='<i></i>API DISCONNECTED · DRY RUN'}}catch{mode='offline'}}finally{r.busy=false}if(await stopOnDeath(r))return;r.history.unshift(r.decision.action);r.history=r.history.slice(0,5);execute(r,r.decision.frame??r.decision.action);render(r,index)}
function render(r:Runner,i:number){const p=r.observation.player,d=r.decision,f=d.frame,label=f?[f.movement,f.view,f.trigger==='FIRE'?'FIRE':'',f.interaction==='USE'?'USE':''].filter(Boolean).join(' + '):d.action;document.querySelector(`#telemetry-${i}`)!.innerHTML=`<div class="statline"><span>HP <strong>${p?.health??'—'}</strong></span><span>ARM <strong>${p?.armor??'—'}</strong></span><span>KILLS <strong>${p?.kills??0}</strong></span></div><div class="decision ${r.fallback?'is-fallback':''}"><b>${label.replaceAll('_',' ')}</b><span>${r.fallback?'API FAILED · STATE-BASED FALLBACK':mode==='live'?'AI CONTROL':'DRY RUN'} · ${d.latency}ms</span></div>`}
async function initialize(){start.disabled=true;start.textContent='INITIALIZING…';runners=await Promise.all(policies.map((p,i)=>boot(document.querySelector<HTMLCanvasElement>(`#doom-${i}`)!,p)));document.querySelectorAll<HTMLTextAreaElement>('textarea').forEach((input,i)=>input.addEventListener('input',()=>runners[i].systemPrompt=input.value.trim()||POLICY_TEXT[policies[i]]));document.querySelectorAll<HTMLButtonElement>('[data-clear-console]').forEach((button,i)=>button.addEventListener('click',()=>{document.querySelector<HTMLPreElement>(`#console-${i}`)!.textContent=''}));document.querySelectorAll<HTMLElement>('.control-pad').forEach((pad,i)=>pad.querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.addEventListener('click',()=>{const control=button.dataset.control!;if(control==='SHOOT'){const frame:ControlFrame={movement:'HOLD_POSITION',view:'FACE_ENEMY',trigger:'FIRE',interaction:'NO_USE'};execute(runners[i],frame,320)}else execute(runners[i],control as Action,320)})));await new Promise<void>(resolve=>{const starting=new Set<number>(),ready=new Set<number>(),poll=window.setInterval(()=>{runners.forEach((r,i)=>{const o=observe(r);if(o.ready&&!starting.has(i)){starting.add(i);window.setTimeout(()=>{initializeStart(r);window.setTimeout(()=>{observe(r);ready.add(i);document.querySelector(`#loading-${i}`)?.remove();render(r,i);logEvent(r,'ENGINE READY',{skill:'easy',visible_enemies:r.observation.visible_enemies?.length??0})},120)},500)}});if(ready.size===runners.length){clearInterval(poll);resolve()}},100)});start.disabled=false;start.textContent='RUN';window.__DEMO_READY__=true}
async function run(){await initializePromise;if(started)return;started=true;deathHandled=false;start.disabled=true;start.textContent='RUNNING';deathMonitor=window.setInterval(()=>{for(const runner of runners){observe(runner);if((runner.observation.player?.health??1)<=0){void stopOnDeath(runner);break}}},100);const schedule=(runner:Runner,index:number,delay:number)=>{timers[index]=window.setTimeout(async()=>{const observation=observe(runner);if(observation.ready){render(runner,index);await decide(runner)}if(started)schedule(runner,index,400)},delay)};runners.forEach((runner,index)=>schedule(runner,index,index*200))}
start.addEventListener('click',()=>void run());initializePromise=initialize();if(q.get('autostart')==='1')void initializePromise.then(run);void fetch('/api/key').then(r=>r.json()).then(s=>{if(s.configured){mode='live';badge.className='badge live';badge.innerHTML='<i></i>LIVE AI CONTROL'}}).catch(()=>{});window.addEventListener('beforeunload',()=>{clearInterval(deathMonitor);timers.forEach(clearInterval);if(mode==='live')void fetch('/api/key',{method:'DELETE',keepalive:true})});
