import { offlineDecision, POLICY_TEXT } from './policy'; import type { Action, Decision, Observation, Policy } from './types';
export type Entity={id:string;x:number;y:number;type:'enemy'|'health'|'armor'|'ammo'|'hazard';hp?:number;alive?:boolean};
export class Simulation {
 x=2;y=7; health=42;armor=10;ammo=6;kills=0; time=0; action:Action='EXPLORE_WORLD'; previous:Action='EXPLORE_WORLD'; decision:Decision; history:Action[]=[]; entities:Entity[]; hurt=14; nextDecision=0;
 constructor(public policy:Policy, public seed=1337){ this.entities=[{id:'enemy_1',x:6,y:4,type:'enemy',hp:45,alive:true},{id:'enemy_2',x:8,y:5,type:'enemy',hp:50,alive:true},{id:'enemy_3',x:10,y:3,type:'enemy',hp:40,alive:true},{id:'medkit_1',x:2,y:8,type:'health'},{id:'armor_1',x:4,y:7,type:'armor'},{id:'ammo_1',x:7,y:7,type:'ammo'},{id:'barrel_1',x:7,y:4,type:'hazard'}]; this.decision=offlineDecision(this.observe(),policy); }
 observe():Observation { const enemies=this.entities.filter(e=>e.type==='enemy'&&e.alive&&Math.hypot(e.x-this.x,e.y-this.y)<7).map(e=>({id:e.id,type:'imp_like',distance:Math.hypot(e.x-this.x,e.y-this.y)<3?'near':'medium' as 'near'|'medium',direction:e.x>this.x?'front':'side',attacking:true,threat:'high' as const})); const pickups=this.entities.filter(e=>['health','armor','ammo'].includes(e.type)&&Math.hypot(e.x-this.x,e.y-this.y)<8).map(e=>({id:e.id,type:e.type,direction:e.x<this.x?'behind_right':'front_right',distance:'medium' as const,reachable:true})); return {player:{health:Math.round(this.health),armor:Math.round(this.armor),weapon:'shotgun',ammo:{shells:this.ammo,bullets:32},recent_damage:this.hurt,under_fire:enemies.length>0},visible_enemies:enemies,visible_pickups:pickups,navigation:{cover:['right'],unexplored_directions:['left','forward'],exit_known:true,exit_direction:'forward'},history:{previous_action:this.previous,current_intent:'engage',stuck_probability:0.02},policy:POLICY_TEXT[this.policy]}; }
 decide(){this.previous=this.action; this.decision=offlineDecision(this.observe(),this.policy);this.action=this.decision.action;this.history.unshift(this.action);this.history=this.history.slice(0,5)}
 step(dt:number){this.time+=dt;if(this.time>=this.nextDecision){this.nextDecision=this.time+.2;this.decide()}const a=this.action,frame=this.decision.frame,move=frame?.movement??a,fire=frame?.trigger==='FIRE'||a==='FIRE',enemy=this.entities.find(e=>e.type==='enemy'&&e.alive);let tx=this.x,ty=this.y;if(enemy&&move==='MOVE_TO_ENEMY'){tx=enemy.x;ty=enemy.y}if(enemy&&move==='RETREAT_FROM_ENEMY'){tx=this.x-(enemy.x-this.x);ty=this.y-(enemy.y-this.y)}const dx=tx-this.x,dy=ty-this.y,d=Math.hypot(dx,dy)||1;this.x+=dx/d*dt*1.65;this.y+=dy/d*dt*1.65;const near=this.entities.filter(e=>e.type==='enemy'&&e.alive&&Math.hypot(e.x-this.x,e.y-this.y)<5);if(near.length){const damage=dt*(move==='RETREAT_FROM_ENEMY'?2:4.5);this.health-=Math.max(0,damage-this.armor*.01);this.hurt=damage*10;if(fire&&this.ammo>0){near[0].hp!-=dt*38;this.ammo=Math.max(0,this.ammo-dt*.8);if(near[0].hp!<=0){near[0].alive=false;this.kills++}}}this.health=Math.max(1,this.health);}
}
